MusicStoreApp/Controllers/MusicStoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStoreApp.Models;

namespace MusicStoreApp.Controllers
{
    public class MusicStoreController : Controller
    {
        

        private MusicStoreDBContext db = new MusicStoreDBContext();

        //
        // GET: /StoreManager/

        public ActionResult Index()
        {
            var albums = db.Albums.Include(a => a.Genre).Include(a => a.Artist);
            return View(albums.ToList());
            
        }

        //
        // GET: /StoreManager/Details/5

        public ActionResult Details(int id = 0)
        {
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // GET: /StoreManager/Create

        public ActionResult Create()
        {
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            return View();
        }

        //
        // POST: /StoreManager/Create

        [HttpPost]
        public ActionResult Create(Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // GET: /StoreManager/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // POST: /StoreManager/Edit/5

        [HttpPost]
        public ActionResult Edit(Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // GET: /StoreManager/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // POST: /StoreManager/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        //public ActionResult Search()
        //{
        //    if (Request.IsAjaxRequest())
        //    {
        //        return PartialView();
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index");
        //    }
          
        //}

        public ActionResult Search()
        {
            if (Request.IsAjaxRequest())
            {
                ViewBag.Genres = new SelectList(db.Genres,"GenreId","Name");
                return PartialView();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

    
        public ActionResult SearchResult(string Genres, string artist, string title, string price)
        {
            //var album1=null;
            List<Album> album1;
            List<Album> album2;
            List<Album> album3;
            List<Album> album4;
            if (Request.IsAjaxRequest())
            {
                if (Genres != "")
                {
                    int genre = Convert.ToInt32(Genres);
                    album1 = db.Albums.Where(a => a.Genre.GenreId.Equals(genre)).ToList();

                    if (artist!="")
                    {
                        album2 = album1.Where(a => a.Artist.Name.Equals(artist)).ToList();

                        if (title!="")
                        {

                            album3 = album2.Where(a => a.Title.Equals(title)).ToList();

                            if (price!="")
                            {
                                decimal p = Convert.ToDecimal(price);
                                album4 = album3.Where(a => a.Price.Equals(p)).ToList();

                                return PartialView(album4);

                            }
                            else
                            {
                                return PartialView(album3);
                            }

                        }
                        else
                        {
                            return PartialView(album2);
                        }
                    }
                    else
                    {
                        return PartialView(album1);
                    }
                }

            }
            else
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        public JsonResult SearchName(string id)
        {
            if (Request.IsAjaxRequest())
            {
                var result = "You have entered : " + id;
                return Json(result,JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data="error from action"});
            }
            
        }

    }
}

MusicStoreApp/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MusicStoreApp.Models;
using System.Data;

namespace MusicStoreApp.Controllers
{
    public class StoreManagerController : Controller
    {

        StoreManagerEntities storeDB = new StoreManagerEntities();

        public ActionResult Index()
        {

            var products = storeDB.Products;
            return View(products.ToList());
        }

        public ActionResult Edit(int id)
        {
            Product product = storeDB.Products.Find(id);
            if (product==null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(product);
            }
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                storeDB.Entry(product).State = EntityState.Modified;
                storeDB.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public ActionResult Details(int id)
        {
            Product product = storeDB.Products.Find(id);
            if (product==null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(product);
            }
        }

    }
}

MusicStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>
                        <img src="~/Images/homelinkimg1.png" />
                    </p>
                    
                    <p class="site-title">@Html.ActionLink("My MVC APPLICATION", "Index", "Home", routeValues: null, htmlAttributes: new { @class="logo"})</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Music Store", "Index", "MusicStore")</li>
                            <li>@Html.ActionLink("Sports Store", "Index", "StoreManager")</li>
                            <li>@Html.ActionLink("Social", "Index", "Social")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.7.1.js")"></script>
        <script type="text/javascript">

            $(document).ready(function () {

                $(".float-left p img").addClass("app-logo");

            });

        </script>

    </body>
</html>

MusicStoreApp/Views/Shared/_LayoutSocial.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>_LayoutSocial</title>
     <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.customize.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-lightbox.min.css" />
    

</head>
<body data-spy="scroll" data-target=".modal .text-info">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="navbar navbar-inverse">
                    <div class="navbar-inner">
                        <a class="brand" href="#">Title</a>
                        <ul class="nav">
                            <li class="active"><a href="/Social/Index"><i class="icon-home icon-white"></i> Home</a></li>
                            <li><a href="/Social/Link1Content" id="link1"><i class="icon-music icon-white"></i> Link 1</a></li>
                            <li><a href="/Social/Link2Content" id="link2"><i class="icon-envelope icon-white"></i> Link 2</a></li>
                        </ul>
                        <form class="navbar-search">
                            <input type="text" placeholder="Search something" id="txtSearch" class="input-medium search-query" />
                        </form>
                        <ul class="nav inline pull-right">
                            <li>
                                <a href="#" id="app_pop" rel="popover" data-content="<div class='container-fluid'><div class='row-fluid'><div class='span4'><a href='#'><i class='icon-music'></i></a></div><div class='span4'><a href='#'><i class='icon-film'></i></a></div><div class='span4'><a href='#'><i class='icon-envelope'></i></a></div></div><div class='row-fluid'><div class='span4'><a href='#'><i class='icon-th-list'></i></a></div><div class='span4'><a href='#'><i class='icon-upload'></i></a></div><div class='span4'><a href='#'><i class='icon-camera'></i></a></div></div><div class='row-fluid'><div class='span4'><a href='#'><i class='icon-picture'></i></a></div><div class='span4'><a href='#'><i class='icon-list'></i></a></div><div class='span4'><a href='#'><i class='icon-map-marker'></i></a></div></div></div>" data-original-title="Apps" data-placement="bottom" data-trigger="click"><i class="icon-th icon-white"></i></a>
                            </li>
                            <li>
                                <a href="#" id="notify_pop" rel="popover" data-content="<div class='container-fluid'><div class='row-fluid'><div class='span2'></div><div class='span8'><img src='/../Images/google.png'/></div><div class='span2'></div></div><div class='row-fluid'><div class='span12'><p class='text-left'><h6>Please <a href='#'>sign in</a> to view your notifications.</h6></p></div></div></div>" data-placement="bottom" data-trigger="click"><i class="icon-bell icon-white"></i></a>
                            </li>
                            <li>
                                <a href="#" id="login_pop" rel="popover" data-content="<div class='container-fluid'><div class='row-fluid'><div class='span12'><form action='/Social/Login' method='post'><label>Username</label><input type='text' name='uname' placeholder='Enter username' class='input-medium' required/><label>Password</label><input type='password' name='password' placeholder='Enter password' class='input-medium' required/><label class='checkbox'><input type='checkbox'/>Remember me</label><button type='submit' class='btn'><i class='icon-thumbs-up'></i>Sign in</button></form></div></div></div>" data-original-title="Login Form" data-placement="bottom" data-trigger="click"><i class="icon-user icon-white"></i> Login</a>
                            </li>
                            <li>
                                <a href="#signup_modal" data-toggle="modal"><i class="icon-arrow-up icon-white"></i> Sign Up</a>
                            </li>
                        </ul>    
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            @RenderBody()
        </div>

                <div id="signup_modal" class="modal hide fade in" style="display:none;">
                            <div class="modal-header" style="background-color:#00BFFF;">
                                <a class="close" data-dismiss="modal">x</a>
                                <h4>User Registration</h4>
                            </div>
                            <div class="modal-body well">
                                <form class="form-horizontal" action="/Social/Register" method="post">
                                    <div class="control-group">
                                            <label class="control-label" for="frmUname"><strong>Username</strong></label>
                                        <div class="controls">
                                            <input type="text" id="frmUname" placeholder="Enter username" name="frmUname" class="input-medium" required />          
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="frmFName"><strong>First Name</strong></label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter first name" class="input-medium" name="frmFName" required />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="frmLName"><strong>Last Name</strong></label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter last name" class="input-medium" name="frmLName" required />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="frmPass"><strong>Password</strong></label>
                                        <div class="controls">
                                            <input type="password" placeholder="Enter password" class="input-medium" name="frmPass" required />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="frmCPass"><strong>Confirm Password</strong></label>
                                        <div class="controls">
                                            <input type="password" placeholder="Confirm password" class="input-medium" name="frmCPass" required />
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="row-fluid">
                                            <div class="span4">

                                            </div>
                                            <div class="span4">
                                                 <label class="radio inline">
                                                 <input type="radio" name="rdbSex" id="rdbMale" value="Male" /> <strong>Male</strong>
                                                 </label>
                                                 <label class="radio inline">
                                                 <input type="radio" name="rdbSex" id="rdbFemale" value="Female" /> <strong>Female</strong>
                                                 </label>
                                            </div>
                                            <div class="span4">

                                            </div>
                                        </div>              
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="frmEmail"><strong>email</strong></label>
                                        <div class="controls">
                                            <input type="email" placeholder="Enter email" class="input-medium" name="frmEmail" required />
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                         <button type="submit" class="btn btn-primary">Submit</button>
                                         <a href="#" class="btn" data-dismiss="modal">Cancel</a>
                                    </div>
                                </form>
                            </div>
                        </div>
    </div>


      <script type="text/javascript" src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.customize.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-lightbox.min.js" ></script>
    <script type="text/javascript" src="~/Scripts/knockout-2.1.0.js"></script>
    <script type="text/javascript" src="~/Scripts/knockout.samples.js"></script>
    <script type="text/javascript" src="~/Scripts/angular.js"></script>
    <script type="text/javascript" src="~/Scripts/angular.samples.js"></script>
    

    <script type="text/javascript">
        $(function () {
            $("#login_pop").popover();
            $("#notify_pop").popover();
            $("#app_pop").popover();
            $('.dropdown-toggle').dropdown();
        });

    </script>

</body>
</html>